############################################################################################
## makefile
##
## Author: Todd Sukolsky
## Initial Build: 2/26/13
## Last Revised: 2/26/13
## Copyright of Todd Sukolsky
##
############################################################################################
## Description: This is a makefile for the "sukolskyShell*" program that is an interactive
## 	shell based on bash. 
############################################################################################
## Revisions: 2/26: Initial Build
##
############################################################################################
## Command summary:
##      	"make"-------------------> makes nothing
##		"clean"------------------> cleans all ~ files
############################################################################################

##Variables
CC=g++
CARGS=-c -Wall

##Protocols
all: clean

clean:
	rm -rf *o
	rm -rf *.c~
	rm -rf *.cpp~
	rm -rf *.h~
	rm -rf *.h.*	
